### PR TITLE
bug fix no categories

### PR DESCRIPTION
**Pull request by dnoneill**

### CODE REVIEW

**Comment by kirschbombe** [comment]
The categories are wrapping:
Screen Shot 2020-10-14 at 3 48 57 PM

**Comment by kirschbombe** [comment]
I noticed this in refactor too, but I had already merged in the last PR, so not sure where it was introduced

**Comment by dnoneill** [comment]
@kirschbombe The wrapping has been fixed on this branch. Also removed the running title on the home page. 

I don't see the IIIF favicon on any of the repo branches. Could you point me to that.

**Comment by kirschbombe** [comment]
I'll see if the IIIF favicon displays again - and I'll check to see if I can find where it's coming from.

**Pull request merged**
