### PR TITLE
add headerimage option

### PR DESCRIPTION
**Pull request by dnoneill**

### CODE REVIEW

**Review by kirschbombe — COMMENTED** [review]
hi, @dnoneill - I pulled down these changes to test and it looks like something is breaking the code. See the attached screenshot. 
Screen Shot 2020-10-06 at 6 13 07 PM
Screen Shot 2020-09-30 at 8 24 51 AM

**Comment by dnoneill** [comment]
@kirschbombe Have you tried it in Firefox. The current branch does that in safari. I has some cross origin blocking for localhost.

**Comment by kirschbombe** [comment]
I haven't tried it in Firefox, but if it's not working in Safari, then we should resolve that before merging it into the master branch. I'll merge it into refactor, but refactor won't be merged until everything is working :) Also, I won't be able to test future PRs if refactor is resulting in a blank page.

**Comment by dnoneill** [comment]
@kirschbombe Should work in Safari locally now.

**Comment by kirschbombe** [comment]
@dnoneill - this fixed it and I merged the changes into refactor, but there shouldn't be a running title on the home page. Can you remove that? Also, the favicon is now a IIIF logo instead of the hexagon image.

**Pull request merged**
